# Generated by Django 4.2.5 on 2023-09-26 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_rename_car_trip_carid_rename_driver_trip_driverid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("lastName", models.CharField(max_length=30)),
                ("dateOfBirth", models.DateField()),
                ("dni", models.IntegerField()),
                ("studentCode", models.IntegerField(default=0)),
                (
                    "schoolId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quotes.school"
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="date",
            new_name="tripDate",
        ),
        migrations.CreateModel(
            name="StudentTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("studentTripCode", models.IntegerField(default=0)),
                (
                    "studentId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quotes.student"
                    ),
                ),
                (
                    "tripId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quotes.trip"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tripSchoolCode", models.IntegerField(default=0)),
                (
                    "schoolId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quotes.school"
                    ),
                ),
                (
                    "tripId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quotes.trip"
                    ),
                ),
            ],
        ),
    ]
