# Generated by Django 4.2.5 on 2023-09-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="schoolCode",
            field=models.IntegerField(default=0),
        ),
    ]
