# Generated by Django 4.2.5 on 2023-09-26 00:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_school_schoolcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="car",
            new_name="carId",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="driver",
            new_name="driverId",
        ),
    ]
